package ars_disciplina.commune.constantia

object ConstantiaNomenTabulae {
    const val NOMEN_TABULAE_GENERA_DISCIPLINAE = "genera_disciplinae"
    const val NOMEN_TABULAE_LATERALIS = "lateralis"
    const val NOMEN_TABULAE_MODUS_ONERIS = "modus_oneris"
    const val NOMEN_TABULAE_ANGULUS = "angulus"
    const val NOMEN_TABULAE_ARCHETYPI = "archetypi"
    const val NOMEN_TABULAE_DISCIPLINAE = "disciplinae"
    const val NOMEN_TABULAE_MOTUS = "motus"
    const val NOMEN_TABULAE_VARIATIONES = "variationes"
    const val NOMEN_TABULAE_GENERA_INSTRUMENTI = "genera_instrumenti"
    const val NOMEN_TABULAE_INSTRUMENTI = "instrumenta"
    const val NOMEN_TABULAE_MUSCULI = "musculi"
    const val NOMEN_TABULAE_MUSCULI_PARS = "musculi_pars"
    const val NOMEN_TABULAE_MUSCULI_REGIO = "musculi_regio"
    const val NOMEN_TABULAE_GENERA_PREHENSIONIOS = "genera_prehensionis"
    const val NOMEN_TABULAE_PREHENSIONES = "prehensiones"
    const val NOMEN_TABULAE_REGULAE = "regulae"

    const val NOMEN_TABULAE_DISCIPLINA_ANGULI = "disciplina_anguli"
    const val NOMEN_TABULAE_DISCIPLINA_ARCHETYPI = "disciplina_archetypi"
    const val NOMEN_TABULAE_DISCIPLINA_GENERA_DISCIPLINAE = "disciplina_genera_disciplinae"
    const val NOMEN_TABULAE_DISCIPLINA_GENERA_PREHENSIONIS = "disciplina_genera_prehensionis"
    const val NOMEN_TABULAE_DISCIPLINA_LATERALITATES = "disciplina_lateralitates"
    const val NOMEN_TABULAE_DISCIPLINA_MODI_ONERIS = "disciplina_modi_oneris"
    const val NOMEN_TABULAE_DISCIPLINA_MOTUS = "disciplina_motus"
    const val NOMEN_TABULAE_DISCIPLINA_PREHENSIONES = "disciplina_prehensiones"
    const val NOMEN_TABULAE_DISCIPLINA_REGULAE = "disciplina_regulae"
    const val NOMEN_TABULAE_DISCIPLINA_VARIATIONES = "disciplina_variationes"

    const val NOMEN_TABULAE_DISCIPLINA_INSTRUMENTI = "disciplina_instrumenti"
    const val NOMEN_TABULAE_DISCIPLINA_GENERA_INSTRUMENTI = "disciplina_genera_instrumenti"
    const val NOMEN_TABULAE_DISCIPLINA_MUSCULI_PARS = "disciplina_musculi_pars"
    const val NOMEN_TABULAE_MUSCULI_PARS_MUSCULI = "musculi_pars_musculi"
    const val NOMEN_TABULAE_MUSCULI_MUSCULI_REGIO = "musculi_musculi_regio"
}