package ars_disciplina.regularum

enum class OmniRegulae {
    EXIGIT_VARIATIONES,
    EXIGIT_TRACTIONEM,
    EXIGIT_PROPULSIONEM,
    EXIGIT_ANGULUM_MINIMUM,
    EXIGIT_ANGULUM_NON_NEGATIVUM,
    EXIGIT_ANGULOS_PERMISSOS,
    EXIGIT_PREHENSIONES,
    EXIGIT_GENUS_PREHENSIONIS,
    EXIGIT_COMPOSITATEM,
    EXIGIT_ISOLATIONEM,
    EXIGIT_UNILATERALITATEM,
    EXIGIT_BILATERALITATEM,
    EXIGIT_LATERALES,
    EXIGIT_MODUM_EXTERNUM,
    EXIGIT_MODUM_CORPORIS,
    EXIGIT_MODUS_ONERIS,
    EXIGIT_GENUS_DISCIPLINAE,
    VETAT_ANGULUM,
    VETAT_PREHENSIONES,
    VETAT_GENUS_PREHENSIONIS
}