ktor {
    deployment {
        port = 8000
    }

    application {
        modules = [
            org.curia_disciplinae.ApplicationKt.module
        ]
    }
}

database {
    jdbcUrl = ${DB_URL}
    username = ${DB_USERNAME}
    password = ${DB_PASSWORD}

    maximumPoolSize = 10
    minimumIdle = 2
}